import { User, Vehicle, Trip, Booking, Review, Conversation, Message, AppNotification, SafetyReport } from './types';

// Curated Moroccan Users
export const MOCK_USERS: Record<string, User> = {
  yassine: {
    id: 'user_yassine',
    first_name: 'Yassine',
    last_name: 'El Mansouri',
    phone: '+212 6 61 23 45 67',
    email: 'yassine.mansouri@routa.ma',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=80',
    city: 'Marrakech',
    rating: 4.8,
    review_count: 127,
    role: 'driver',
    verification_status: {
      phone: true,
      identity: true,
      license: true,
      vehicle: true,
    },
    trips_as_driver: 127,
    trips_as_passenger: 14,
    created_at: '2024-03-12',
    vehicle_id: 'veh_yassine',
  },
  imane: {
    id: 'user_imane',
    first_name: 'Imane',
    last_name: 'Benjelloun',
    phone: '+212 6 62 98 76 54',
    email: 'imane.benjelloun@routa.ma',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&h=200&q=80',
    city: 'Marrakech',
    rating: 4.9,
    review_count: 98,
    role: 'passenger',
    verification_status: {
      phone: true,
      identity: true,
      license: true,
      vehicle: true,
    },
    trips_as_driver: 6,
    trips_as_passenger: 36,
    created_at: '2024-05-20',
    vehicle_id: 'veh_imane',
  },
  karim: {
    id: 'user_karim',
    first_name: 'Karim',
    last_name: 'Tazi',
    phone: '+212 6 63 11 22 33',
    email: 'karim.tazi@routa.ma',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=80',
    city: 'Marrakech',
    rating: 4.7,
    review_count: 64,
    role: 'driver',
    verification_status: {
      phone: true,
      identity: true,
      license: true,
      vehicle: true,
    },
    trips_as_driver: 64,
    trips_as_passenger: 8,
    created_at: '2024-07-15',
    vehicle_id: 'veh_karim',
  },
  sara: {
    id: 'user_sara',
    first_name: 'Sara',
    last_name: 'Alami',
    phone: '+212 6 64 44 55 66',
    email: 'sara.alami@routa.ma',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&h=200&q=80',
    city: 'Marrakech',
    rating: 4.8,
    review_count: 42,
    role: 'driver',
    verification_status: {
      phone: true,
      identity: true,
      license: true,
      vehicle: true,
    },
    trips_as_driver: 42,
    trips_as_passenger: 19,
    created_at: '2024-08-01',
    vehicle_id: 'veh_sara',
  },
  fatima: {
    id: 'user_fatima',
    first_name: 'Fatima',
    last_name: 'Zahra',
    phone: '+212 6 65 77 88 99',
    email: 'fatima.z@routa.ma',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&h=200&q=80',
    city: 'Marrakech',
    rating: 5.0,
    review_count: 18,
    role: 'passenger',
    verification_status: {
      phone: true,
      identity: true,
      license: false,
      vehicle: false,
    },
    trips_as_driver: 0,
    trips_as_passenger: 22,
    created_at: '2024-09-10',
  },
  omar: {
    id: 'user_omar',
    first_name: 'Omar',
    last_name: 'Berrada',
    phone: '+212 6 66 12 34 89',
    email: 'omar.berrada@routa.ma',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&h=200&q=80',
    city: 'Marrakech',
    rating: 4.9,
    review_count: 31,
    role: 'passenger',
    verification_status: {
      phone: true,
      identity: true,
      license: true,
      vehicle: false,
    },
    trips_as_driver: 0,
    trips_as_passenger: 35,
    created_at: '2024-06-04',
  },
  admin: {
    id: 'user_admin',
    first_name: 'Admin',
    last_name: 'Routa Maroc',
    phone: '+212 5 22 00 00 00',
    email: 'contact@routa.ma',
    photo: '',
    city: 'Casablanca',
    rating: 5.0,
    review_count: 500,
    role: 'admin',
    verification_status: {
      phone: true,
      identity: true,
      license: true,
      vehicle: true,
    },
    trips_as_driver: 0,
    trips_as_passenger: 0,
    created_at: '2024-01-01',
  },
};

// Vehicles
export const MOCK_VEHICLES: Record<string, Vehicle> = {
  veh_yassine: {
    id: 'veh_yassine',
    user_id: 'user_yassine',
    brand: 'Dacia',
    model: 'Logan',
    color: 'Blanche',
    year: 2020,
    plate: '12345 | A | 6', // Marrakech
    seats: 4,
    verified: true,
  },
  veh_imane: {
    id: 'veh_imane',
    user_id: 'user_imane',
    brand: 'Hyundai',
    model: 'i20',
    color: 'Grise',
    year: 2022,
    plate: '67890 | B | 6',
    seats: 4,
    verified: true,
  },
  veh_karim: {
    id: 'veh_karim',
    user_id: 'user_karim',
    brand: 'Peugeot',
    model: '301',
    color: 'Noire',
    year: 2021,
    plate: '43210 | D | 6',
    seats: 4,
    verified: true,
  },
  veh_sara: {
    id: 'veh_sara',
    user_id: 'user_sara',
    brand: 'Kia',
    model: 'Picanto',
    color: 'Rouge',
    year: 2019,
    plate: '98765 | H | 6',
    seats: 4,
    verified: true,
  },
};

// Trips (Matching exact mockup and intelligent corridor matching)
export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip_yassine_1',
    driver_id: 'user_yassine',
    driver: MOCK_USERS.yassine,
    vehicle: MOCK_VEHICLES.veh_yassine,
    origin: 'Targa, Marrakech',
    origin_lat: 31.6425,
    origin_lng: -8.0418,
    destination: 'Médina, Marrakech',
    destination_lat: 31.6295,
    destination_lng: -7.9811,
    corridor: [
      { id: 'c1', name: 'Targa', approx_time: '08:00', lat: 31.6425, lng: -8.0418, type: 'origin' },
      { id: 'c2', name: 'Guéliz', approx_time: '08:15', lat: 31.6346, lng: -8.0125, type: 'stop' },
      { id: 'c3', name: 'Hivernage', approx_time: '08:25', lat: 31.6241, lng: -8.0054, type: 'stop' },
      { id: 'c4', name: 'Médina', approx_time: '08:35', lat: 31.6295, lng: -7.9811, type: 'destination' },
    ],
    date: "Aujourd'hui",
    departure_time: '08:00',
    estimated_duration_min: 35,
    distance_km: 12,
    available_seats: 4,
    reserved_seats: 2,
    global_price: 15,
    passenger_contribution: 10,
    fuel_cost_dh: 10,
    wear_cost_dh: 4,
    toll_cost_dh: 0,
    status: 'PARTIALLY_BOOKED',
    match_type: 'exact',
    compatibility_score: 98,
    passengers: [
      {
        id: 'user_fatima',
        name: 'Fatima',
        photo: MOCK_USERS.fatima.photo,
        pickup_point: 'Targa',
        dropoff_point: 'Guéliz',
        seats: 1,
        contribution_dh: 10,
      },
      {
        id: 'user_omar',
        name: 'Omar',
        photo: MOCK_USERS.omar.photo,
        pickup_point: 'Guéliz',
        dropoff_point: 'Médina',
        seats: 1,
        contribution_dh: 10,
      },
    ],
    created_at: '2026-10-01T07:00:00Z',
  },
  {
    id: 'trip_sara_2',
    driver_id: 'user_sara',
    driver: MOCK_USERS.sara,
    vehicle: MOCK_VEHICLES.veh_sara,
    origin: 'Guéliz, Marrakech',
    origin_lat: 31.6346,
    origin_lng: -8.0125,
    destination: 'Hivernage, Marrakech',
    destination_lat: 31.6241,
    destination_lng: -8.0054,
    corridor: [
      { id: 'ci1', name: 'Guéliz (Plaza)', approx_time: '08:30', lat: 31.6346, lng: -8.0125, type: 'origin' },
      { id: 'ci2', name: 'Bd Mohammed V', approx_time: '08:40', lat: 31.6300, lng: -8.0090, type: 'stop' },
      { id: 'ci3', name: 'Hivernage', approx_time: '08:45', lat: 31.6241, lng: -8.0054, type: 'destination' },
    ],
    date: "Aujourd'hui",
    departure_time: '08:30',
    estimated_duration_min: 15,
    distance_km: 4.5,
    available_seats: 4,
    reserved_seats: 1,
    global_price: 10,
    passenger_contribution: 10,
    fuel_cost_dh: 4,
    wear_cost_dh: 2,
    toll_cost_dh: 0,
    status: 'PARTIALLY_BOOKED',
    match_type: 'compatible',
    compatibility_score: 84,
    passengers: [
      {
        id: 'user_salma',
        name: 'Salma',
        photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&h=200&q=80',
        pickup_point: 'Guéliz (Plaza)',
        dropoff_point: 'Hivernage',
        seats: 1,
        contribution_dh: 10,
      },
    ],
    created_at: '2026-10-01T07:15:00Z',
  },
  {
    id: 'trip_karim_1',
    driver_id: 'user_karim',
    driver: MOCK_USERS.karim,
    vehicle: MOCK_VEHICLES.veh_karim,
    origin: 'Targa, Marrakech',
    origin_lat: 31.6425,
    origin_lng: -8.0418,
    destination: 'Guéliz, Marrakech',
    destination_lat: 31.6346,
    destination_lng: -8.0125,
    corridor: [
      { id: 'ck1', name: 'Targa Carrefour', approx_time: '09:00', lat: 31.6425, lng: -8.0418, type: 'origin' },
      { id: 'ck2', name: 'Route de Targa', approx_time: '09:12', lat: 31.6380, lng: -8.0270, type: 'stop' },
      { id: 'ck3', name: 'Guéliz Gare ONCF', approx_time: '09:20', lat: 31.6346, lng: -8.0125, type: 'destination' },
    ],
    date: "Aujourd'hui",
    departure_time: '09:00',
    estimated_duration_min: 20,
    distance_km: 7.8,
    available_seats: 4,
    reserved_seats: 3,
    global_price: 10,
    passenger_contribution: 10,
    fuel_cost_dh: 7,
    wear_cost_dh: 3,
    toll_cost_dh: 0,
    status: 'PARTIALLY_BOOKED',
    match_type: 'exact',
    compatibility_score: 92,
    passengers: [
      {
        id: 'p1',
        name: 'Mehdi',
        photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&h=200&q=80',
        pickup_point: 'Targa Carrefour',
        dropoff_point: 'Guéliz Gare ONCF',
        seats: 1,
        contribution_dh: 10,
      },
      {
        id: 'p2',
        name: 'Khadija',
        photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&h=200&q=80',
        pickup_point: 'Targa Carrefour',
        dropoff_point: 'Route de Targa',
        seats: 1,
        contribution_dh: 10,
      },
      {
        id: 'p3',
        name: 'Hamza',
        photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200&q=80',
        pickup_point: 'Route de Targa',
        dropoff_point: 'Guéliz Gare ONCF',
        seats: 1,
        contribution_dh: 10,
      },
    ],
    created_at: '2026-10-01T07:30:00Z',
  },
  {
    id: 'trip_sara_1',
    driver_id: 'user_sara',
    driver: MOCK_USERS.sara,
    vehicle: MOCK_VEHICLES.veh_sara,
    origin: 'Sidi Ghanem, Marrakech',
    origin_lat: 31.6675,
    origin_lng: -8.0284,
    destination: 'Médina, Marrakech',
    destination_lat: 31.6295,
    destination_lng: -7.9811,
    corridor: [
      { id: 'cs1', name: 'Sidi Ghanem', approx_time: '08:15', lat: 31.6675, lng: -8.0284, type: 'origin' },
      { id: 'cs2', name: 'Semlalia', approx_time: '08:25', lat: 31.6450, lng: -8.0100, type: 'stop' },
      { id: 'cs3', name: 'Bab Doukkala (Médina)', approx_time: '08:35', lat: 31.6295, lng: -7.9811, type: 'destination' },
    ],
    date: "Aujourd'hui",
    departure_time: '08:15',
    estimated_duration_min: 22,
    distance_km: 8.5,
    available_seats: 4,
    reserved_seats: 3,
    global_price: 11,
    passenger_contribution: 10,
    fuel_cost_dh: 8,
    wear_cost_dh: 3,
    toll_cost_dh: 0,
    status: 'PARTIALLY_BOOKED',
    match_type: 'compatible',
    compatibility_score: 79,
    passengers: [
      {
        id: 'ps1',
        name: 'Amine',
        photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&h=200&q=80',
        pickup_point: 'Sidi Ghanem',
        dropoff_point: 'Bab Doukkala',
        seats: 1,
        contribution_dh: 12,
      },
      {
        id: 'ps2',
        name: 'Nadia',
        photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&h=200&q=80',
        pickup_point: 'Semlalia',
        dropoff_point: 'Bab Doukkala',
        seats: 2,
        contribution_dh: 24,
      },
    ],
    created_at: '2026-10-01T07:45:00Z',
  },
  {
    id: 'trip_intercity_1',
    driver_id: 'user_yassine',
    driver: MOCK_USERS.yassine,
    vehicle: MOCK_VEHICLES.veh_yassine,
    origin: 'Marrakech (Gare ONCF)',
    origin_lat: 31.6346,
    origin_lng: -8.0125,
    destination: 'Casablanca (Casa Port)',
    destination_lat: 33.5992,
    destination_lng: -7.6114,
    corridor: [
      { id: 'c_cas1', name: 'Marrakech (Gare ONCF)', approx_time: '14:00', lat: 31.6346, lng: -8.0125, type: 'origin' },
      { id: 'c_cas2', name: 'Ben Guerir (Péage)', approx_time: '14:45', lat: 32.2340, lng: -7.9540, type: 'stop' },
      { id: 'c_cas3', name: 'Settat (Sortie)', approx_time: '15:35', lat: 33.0010, lng: -7.6160, type: 'stop' },
      { id: 'c_cas4', name: 'Casablanca (Casa Port)', approx_time: '16:30', lat: 33.5992, lng: -7.6114, type: 'destination' },
    ],
    date: 'Demain',
    departure_time: '14:00',
    estimated_duration_min: 150,
    distance_km: 240,
    available_seats: 4,
    reserved_seats: 1,
    global_price: 380,
    passenger_contribution: 95,
    fuel_cost_dh: 200,
    wear_cost_dh: 85,
    toll_cost_dh: 82,
    status: 'PARTIALLY_BOOKED',
    match_type: 'exact',
    compatibility_score: 95,
    passengers: [
      {
        id: 'user_omar',
        name: 'Omar',
        photo: MOCK_USERS.omar.photo,
        pickup_point: 'Marrakech (Gare ONCF)',
        dropoff_point: 'Casablanca (Casa Port)',
        seats: 1,
        contribution_dh: 95,
      }
    ],
    created_at: '2026-10-01T08:00:00Z',
  },
];

// Bookings
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'book_imane_yassine_1',
    trip_id: 'trip_yassine_1',
    passenger_id: 'user_imane',
    passenger: MOCK_USERS.imane,
    trip: MOCK_TRIPS[0],
    seats_reserved: 1,
    pickup_point: 'Targa (Rond-point)',
    dropoff_point: 'Médina (Bab Doukkala)',
    passenger_price: 15,
    status: 'CONFIRMED',
    created_at: '2026-10-01T07:35:00Z',
  },
];

// Conversations and Messages
export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_yassine_imane',
    trip_id: 'trip_yassine_1',
    participants: [MOCK_USERS.yassine, MOCK_USERS.imane],
    last_message: 'Parfait, je serai au point indiqué.',
    last_message_time: '07:44',
    unread_count: 0,
  },
  {
    id: 'conv_karim_imane',
    trip_id: 'trip_karim_1',
    participants: [MOCK_USERS.karim, MOCK_USERS.imane],
    last_message: 'Départ confirmé à 09:00 pile devant la banque.',
    last_message_time: 'Hier',
    unread_count: 1,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  conv_yassine_imane: [
    {
      id: 'm1',
      conversation_id: 'conv_yassine_imane',
      sender_id: 'user_imane',
      text: 'Bonjour, vous passez bien par Guéliz ?',
      created_at: '2026-10-01T07:42:00Z',
      time: '07:42',
      read: true,
    },
    {
      id: 'm2',
      conversation_id: 'conv_yassine_imane',
      sender_id: 'user_yassine',
      text: 'Oui, je passe par Guéliz vers 08h15.',
      created_at: '2026-10-01T07:43:00Z',
      time: '07:43',
      read: true,
    },
    {
      id: 'm3',
      conversation_id: 'conv_yassine_imane',
      sender_id: 'user_imane',
      text: 'Parfait, je serai au point indiqué.',
      created_at: '2026-10-01T07:44:00Z',
      time: '07:44',
      read: true,
    },
  ],
};

// Reviews
export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    trip_id: 'trip_past_1',
    author_id: 'user_fatima',
    author_name: 'Fatima Z.',
    author_photo: MOCK_USERS.fatima.photo,
    target_user_id: 'user_yassine',
    target_user_name: 'Yassine El Mansouri',
    rating: 5,
    punctuality: 5,
    respect: 5,
    communication: 5,
    driving_or_reliability: 5,
    comment: 'Conducteur ponctuel, voiture très propre et conduite très douce sur la route de Targa.',
    created_at: '2026-09-28',
  },
  {
    id: 'rev_2',
    trip_id: 'trip_past_2',
    author_id: 'user_omar',
    author_name: 'Omar B.',
    author_photo: MOCK_USERS.omar.photo,
    target_user_id: 'user_yassine',
    target_user_name: 'Yassine El Mansouri',
    rating: 5,
    punctuality: 5,
    respect: 5,
    communication: 4,
    driving_or_reliability: 5,
    comment: 'Super expérience ! Trajet rapide, discussion agréable et respect des horaires.',
    created_at: '2026-09-24',
  },
];

// Notifications
export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    user_id: 'user_imane',
    type: 'BOOKING_CONFIRMED',
    title: 'Réservation confirmée !',
    message: 'Votre place avec Yassine (Targa → Médina, 08:00) est confirmée. Préparez-vous à l’arrêt.',
    read: false,
    created_at: 'Il y a 10 min',
  },
  {
    id: 'notif_2',
    user_id: 'user_imane',
    type: 'NEW_MESSAGE',
    title: 'Nouveau message de Karim',
    message: 'Départ confirmé à 09:00 pile devant la banque.',
    read: false,
    created_at: 'Il y a 1 heure',
  },
  {
    id: 'notif_3',
    user_id: 'user_imane',
    type: 'TRIP_REMINDER',
    title: 'Rappel de trajet',
    message: 'Votre covoiturage vers la Médina démarre aujourd’hui à 08:00.',
    read: true,
    created_at: 'Hier',
  },
];

// Safety Reports for Back-Office
export const MOCK_REPORTS: SafetyReport[] = [
  {
    id: 'rep_1',
    author_id: 'user_fatima',
    author_name: 'Fatima Z.',
    target_user_id: 'user_unknown',
    target_user_name: 'Adil K.',
    trip_id: 'trip_998',
    reason: 'Retard excessif injustifié (+35min)',
    details: 'Le conducteur est arrivé avec plus de 35 minutes de retard sans prévenir au préalable par chat.',
    status: 'IN_REVIEW',
    created_at: '2026-09-30',
  },
  {
    id: 'rep_2',
    author_id: 'user_omar',
    author_name: 'Omar B.',
    target_user_id: 'user_unknown_2',
    target_user_name: 'Rachid M.',
    reason: 'Profil véhicule non conforme',
    details: 'La couleur du véhicule ne correspondait pas aux informations déclarées sur la fiche.',
    status: 'RESOLVED',
    created_at: '2026-09-25',
  },
];
